DROP TABLE MYNONG CASCADE CONSTRAINTS;

DROP TABLE MEMBER CASCADE CONSTRAINTS;

DROP TABLE CALBOARD CASCADE CONSTRAINTS;

DROP TABLE ACCOUNT CASCADE CONSTRAINTS;

DROP TABLE NONG CASCADE CONSTRAINTS;

DROP TABLE NONG_CO CASCADE CONSTRAINTS;

DROP TABLE NONGDELETE_FILE CASCADE CONSTRAINTS;

DROP TABLE JIK CASCADE CONSTRAINTS;

DROP TABLE JIK_COMM CASCADE CONSTRAINTS;

DROP TABLE JIK_LIKE CASCADE CONSTRAINTS;

DROP TABLE JIK_FILES CASCADE CONSTRAINTS;

DROP TABLE FREE CASCADE CONSTRAINTS;

DROP TABLE FREE_COMM CASCADE CONSTRAINTS;

DROP TABLE FREE_LIKE CASCADE CONSTRAINTS;

DROP TABLE FREE_FILES CASCADE CONSTRAINTS;

DROP TABLE DELETE_FILE CASCADE CONSTRAINTS;

DROP TABLE CATEGORY CASCADE CONSTRAINTS;

DROP TABLE PRODUCT CASCADE CONSTRAINTS;

DROP TABLE CART CASCADE CONSTRAINTS;

DROP TABLE ORDER_MARKET CASCADE CONSTRAINTS;

DROP TABLE ORDER_DETAIL CASCADE CONSTRAINTS;

DROP TABLE NOTICE CASCADE CONSTRAINTS;

DROP TABLE REPORT CASCADE CONSTRAINTS;





