DROP TABLE MEMBER;

CREATE TABLE MEMBER(
	ID				VARCHAR2(50)	NOT NULL	PRIMARY KEY,
	PASS			VARCHAR2(50)	NOT NULL,
	NAME			VARCHAR2(50),
	NICK			VARCHAR2(50)	NOT NULL,
	MAIL			VARCHAR2(50),
	TEL				VARCHAR2(50),
	MY_FARM			VARCHAR2(1),
	PERSNACON		VARCHAR2(50),
	POINT			NUMBER(7),
	MYNONG_NAME		VARCHAR2(50)	REFERENCES mynong(MYNONG_NAME),
	CONSTRAINT MEMBER_uq UNIQUE (NICK)
);

SELECT * FROM MEMBER;

INSERT INTO MEMBER(ID, PASS, NAME, NICK, MAIL, TEL, MY_FARM, PERSNACON, POINT, MYNONG_NAME)
VALUES('admin', '1234', '관리자', '관리자', 'admin@gmail.com', '01012345678', '1', 'null', 0, '');

INSERT INTO member
VALUES('user', '1234', '유저', '유저1', 'user@gmail.com', '01012345678', '0', 'null', 0, '');





