drop table MEMBER  cascade constraints;

CREATE TABLE MEMBER(
	ID			VARCHAR2(50)	NOT NULL,
	PASS		VARCHAR2(50)	NOT NULL,
	NAME		VARCHAR2(50),
	NICK		VARCHAR2(50)	NOT NULL,
	MAIL		VARCHAR2(50),
	TEL			VARCHAR2(50),
	MY_FARM		VARCHAR2(1),
	PERSNACON	VARCHAR2(50),
	POINT		NUMBER(7),
	MYNONG_NAME	VARCHAR2(50),
	PRIMARY KEY (ID),
	UNIQUE KEY (NICK),
	REFERENCES mynong(MYNONG_NAME)
);

select * from MEMBER;