drop table product  cascade constraints;

delete from product;

CREATE TABLE PRODUCT(
  PRODUCT_CODE       VARCHAR2(6),          		-- 상품코드 
  CATEGORY_CODE      VARCHAR2(50)	not null,   -- 카테고리 코드 
  PRODUCT_NAME       VARCHAR2(50)	not null,   -- 상품명 
  PRODUCT_PRICE   	 NUMBER(10)		not null,   -- 상품 가격 
  PRODUCT_DETAIL     VARCHAR2(100)	not null,   -- 상세 정보 
  PRODUCT_IMG        VARCHAR2(50)	not null,   -- 실제 저장된 이미지이름 
  PRODUCT_ORIGINAL   VARCHAR2(50)	not null,   -- 첨부될 파일 명 
  PRODUCT_DATE	     VARCHAR2(50)	not null,   -- 상품등록일    
  PRIMARY KEY(PRODUCT_CODE),
  FOREIGN KEY (CATEGORY_CODE) REFERENCES CATEGORY (CATEGORY_CODE)
);

select * from product;
  
  
INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000001', '600', '주말 장바구니(소)', '4000', '오래 쓸 수 있는 튼튼한 장바구니', '장바구니_소.jpg', '장바구니_소.jpg', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000002', '600', '주말 장바구니(중)', '6000', '오래 쓸 수 있는 튼튼한 장바구니', '장바구니_중.jpg', '장바구니_중.jpg', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000003', '300', '대유 모두나와(500ml)', '11500', '고추 토마토 딸기 작물 총채벌레 진딧물 해충 유인제', '대유_모두나와.png', '대유_모두나와.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000004', '300', '대유 응진싹', '8900', '응애 진딧물 온실가루이 해충퇴치 천연추출물 효과 빠른 살충제', '대유_응진싹.png', '대유_응진싹.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000005', '300', '유일 잎끝마름에(300ml)', '13500', '고추 대파 양파 마늘 쪽파 잎마름병 예방 치료 살충 살균제', '잎끝마름에.png', '잎끝마름에.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000006', '300', '대유 나르겐골드(500ml)', '8500', '식물활력 생육증진 맛 색깔 개선 영양제', '나르겐골드.png', '나르겐골드.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000007', '300', '대유 과비대애(500ml)', '14500', '비대제 사과 감귤 포도 복숭아 배 과일 나무 비료 당도 영양제', '대유_과비대애.png', '대유_과비대애.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000008', '300', '초주금 골드(500ml)', '13000', '친환경 잡초관리제 잡초제거제 농약 제초제 말고 그라목손 근사미', '초주금.png', '초주금.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000009', '300', '청충불패', '24500', '선녀벌레 뿌리파리 나방 고추 진딧물 유기농 살충제 해충관리', '청충불패.png', '청충불패.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000010', '300', '뉴 톡깍이파워(250ml)', '25000', '톡토기 깍지벌레 살충제 퇴치 친환경 고추 배추 해충관리제 진딧물', '뉴_톡깍이파워.png', '뉴_톡깍이파워.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000011', '300', '옥시-팜(100g)', '50000', '강력한 토양개량제 고추 딸기 비료 영양제 아쿠도 루핸스 한국농수산', '옥시팜.png', '옥시팜.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000012', '300', '오복이(500ml/1L)', '20000', '수용성 유황 규산 고추 탄저병 유기농 영양제 칼슘제 비료', '오복이.png', '오복이.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000013', '300', '대유 뿌리커(500ml)', '8800', '감자 고추 고구마 배추 마늘 양파 비대 구근 비대 뿌리활착 전용', '대유_뿌리커.png', '대유_뿌리커.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000014', '100', '오복꿀', '60000', '참외씨앗 오복꿀 500립 명품 참외종자 농우바이오', '오복꿀.png', '오복꿀.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000015', '100', '칼라짱', '1300000', '고추씨앗 1200립 극대롸 탄저병 칼라병 예방 고추종자 농우바이오', '칼라짱.png', '칼라짱.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000016', '100', '백봉다다기', '15000', '농우바이오 백다다기 백봉 오이씨앗 종자 500립 백봉다다기 오이', '백봉다다기.png', '백봉다다기.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000017', '100', '추월배추', '14500', '추월배추 2021년포장 뿌리혹병 노균병 바이러스에 강한 김장배추 씨앗 종자', '추월배추.png', '추월배추.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000018', '100', '베타500', '11000', '베타500 김장배추 종자 300립 항암효과 베타카로틴 가을 황금배추', '베타500.png', '베타500.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000019', '100', '청진플러스', '4000', '농가왕무 백청무 추성무 가을무 김장무씨앗 청진플러스', '청진플러스.png', '청진플러스.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000020', '100', '알타리무 천사무 홍반장무', '4500', '홍반장무 알타리무 총각무 달랑무 가을무 종자 농우바이오', '홍반장무.png', '홍반장무.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000021', '100', '롱그린맛', '70000', '롱그린 오이고추 고추씨앗 1000립 아삭이 바이러스예방 종자 농우바이오', '롱그린맛.png', '롱그린맛.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000022', '100', '부추모종', '1090', '부추모종 숱이많은 부추 잎줄기 채소 야채', '부추모종.png', '부추모종.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000023', '100', '고수모종', '990', '고수모종 소화도움 한방 약재 잎줄기 채소 야채', '고수모종.png', '고수모종.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000024', '100', '쪽파모종', '390', '쪽파모종 비타민A 면역력 증진 잎줄기 채소 야채', '쪽파모종.png', '쪽파모종.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000025', '100', '케일모종(2포트)', '790', '케일모종 비타민A 면역력 증진 잎줄기 채소 야채', '케일모종.png', '케일모종.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000026', '100', '아삭이상추모종(2포트)', '790', '아삭이상추모종 일반 상추보다 두껍고 단맛 색 선명 잎줄기 채소 야채', '아삭이상추모종.png', '아삭이상추모종.png', sysdate);

----200번(비료/상토) 카테고리 -------

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000027', '200', '천연부엽토(대지개발)20kg', '7000', '천연부엽토(대지개발) 상토 퇴비 비료 마사토 흙', '천연부엽토.png', '천연부엽토.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000028', '200', '생명정(대지개발)20kg', '7900', '생명정(대지개발) 상토 퇴비 비료 영양제 마사토', '생명정.png', '생명정.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000029', '200', '나르겐2000 500g', '5600', '나르겐 2000 대유 500g 영양제 거름 퇴비 식물영양보충제', '나르겐2000.png', '나르겐2000.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000030', '200', '스페셜 텃밭용 35L', '12000', '텃밭 주말농장흙 스페셜 발효수피 35L 거름 분갈이원예용상토 주말농장', '텃밭용.png', '텃밭용.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000031', '200', '고추비료 800g', '5000', '고추비료 800g 웃거름용 고형비료 주말농장 텃밭용', '고추비료.png', '고추비료.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000032', '200', '원예일품 20kg', '18000', '고품질 채소 복합비료 주말농장 텃밭용 고추 호박 딸기 배 사과 유실수', '원예일품.png', '원예일품.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000033', '200', '넘버원 BIO 발효 수피', '3000', '텃밭 주말농장흙 스페셜 발효수피 8L 거름 분갈이원예용상토 주말농장', '넘버원.png', '넘버원.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000034', '200', '키우미 40L', '12300', '원예용상토 다육이분갈이 화분 흙 코코넛껍질 코코피트 40L', '키우미.png', '키우미.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000035', '200', '바로커 50L', '11300', '바로커 상토 50L 원예용 상토 화분갈이흙 배양토', '바로커.png', '바로커.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000036', '200', '토토유박 20kg', '13000', '최상품 유박비료 유기질 퇴비 고추 깻묵 거름 친환경 화초 텃밭', '토토유박.png', '토토유박.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000037', '200', '아리존 유기질 20kg', '11000', '유기질 유박 비료 깻묵 미강 계분 유기농 퇴비 화분 텃밭', '아리존.png', '아리존.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000038', '200', '롱런 20kg', '18000', '최고급 완효성비료 6개월지속 복합비료 블루베리 밑 웃 거름 과수 원예', '롱런.png', '롱런.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000039', '200', '콩땅콩비료 20kg', '14000', '풍농 콩 땅콩 비료 참깨 들깨 깨전용비료 20kg 두류작물 전용 복합', '콩땅콩비료.png', '콩땅콩비료.png', sysdate);

----400번(농기구) 카테고리 -------

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000040', '400', '마늘캐는도구', '22700', '마늘캐는 도구 마늘캐는 기계 감자캐는 기계', '마늘캐는기계.png', '마늘캐는기계.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000041', '400', '작업방석', '4220', '농사용 작업방석 밭일 엉덩이 의자', '작업방석.png', '작업방석.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000042', '400', '고구마 이식기', '3000', '고구마이식기 고구마순심기', '고구마이식기.png', '고구마이식기.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000043', '400', '고추지지대', '630', '고추지지대 1.8M 낱개 국산 고추대 지주대 식물지지대', '고추지지대.png', '고추지지대.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000044', '400', '포크삽', '9500', '포크삽 쇠스랑포크삽 특수재질 탄소강그립 마호가니 목재사용', '포크삽.png', '포크삽.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000045', '400', '천공삽', '7200', '천공삽 흙돌 농기구 농사 조경 원예', '천공삽.png', '천공삽.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000046', '400', '철막삽', '9000', '철막삽 막삽 농기구 농사 조경 원예', '철막삽.png', '철막삽.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000047', '400', '명품낫', '1200', '명품낫(나무자루) 다용도낫 특제낫 벌초 예초 농기구 낫', '명품낫.png', '명품낫.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000048', '400', '단호조파', '7900', '코알라 단호조파 (나무자루포함)', '단호조파.png', '단호조파.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000049', '400', '마늘쫑고지가위', '11200', '마늘쫑고지가위 신성 600mm X30-2 적과가위', '마늘쫑고지가위.png', '마늘쫑고지가위.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000050', '400', '우레탄곡괭이', '9700', '우레탄곡괭이 반평 완평 양뿔 곡괭이 우레탄 농기구 호미 낫 삽 자루', '우레탄곡괭이.png', '우레탄곡괭이.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000051', '400', '스텐꽃삽', '2000', '스텐꽃삽 모종삽 분삽 원예 농장 텃밭관리', '스텐꽃삽.png', '스텐꽃삽.png', sysdate);

----600번(굿즈) 카테고리 -------

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000052', '600', '텀블러', '12000', '스테인리스 텀블러 500Ml 하루종이 보온 보냉', 'tumbler.jpg', 'tumbler.jpg', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000053', '600', '작업방석', '2000', '푹신한 작업용방석 이거 없이 밭일 못해요', '주말작업방석.png', '주말작업방석.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000054', '600', '반팔티', '5900', '쿨반팔티 냉감 작업용 여름 냉감쿨티셔츠', '반팔티.png', '반팔티.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000055', '600', '농부 모자', '7000', '햇빛가리개 차광 작업모자 농사모자 자외선차단', '농부모자.png', '농부모자.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000056', '600', '팔토시', '8300', '여름 냉감 쿨토시 손토시 롱쿨 햇빛가리개', '팔토시.png', '팔토시.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000057', '600', '초록 몸빼바지', '10000', '면슬라브 몸빼 작업용 고무줄 바지 프리사이즈', '몸빼바지.png', '몸빼바지.png', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000058', '600', '주말머그', '5000', '오렌지 주말농장 머그 350ml', 'mug.jpg', 'mug.jpg', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000059', '600', '주말타올', '2000', '땀닦기 좋은 휴대용 타월 오렌지 타월 흡수 건조 굿', 'towel.jpeg', 'towel.jpeg', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000060', '600', '손가락장갑', '2000', '채소 과일 꼭지 절단 손가락 장갑 고무 장갑', '손가락장갑.jpg', '손가락장갑.jpg', sysdate);

INSERT INTO PRODUCT(PRODUCT_CODE, CATEGORY_CODE, PRODUCT_NAME, PRODUCT_PRICE ,
PRODUCT_DETAIL, PRODUCT_IMG, PRODUCT_ORIGINAL, PRODUCT_DATE)
VALUES('000061', '600', '작업용장갑', '3000', '작업용 장갑 라텍스 장갑 손등까지 라텍스 긴 손목', '라텍스장갑.png', '라텍스장갑.png', sysdate);
