DROP TABLE ACCOUNT cascade constraints;

CREATE TABLE ACCOUNT (
SEQ         NUMBER              NOT NULL PRIMARY KEY,  -- 가계부 번호--
NAME        VARCHAR2(50)        NOT NULL, -- 농장 이름--
TITLE       VARCHAR2(1000)      NOT NULL, -- 지출 명--
CONTENT     VARCHAR2(4000)              , -- 지출 내역 세부정보--
AMOUNT      VARCHAR2(30)           NOT NULL, -- 지출 금액--
MDATE       VARCHAR2(12)        NOT NULL, -- 지출 시간--
foreign key (NAME) REFERENCES mynong(MYNONG_NAME)
);

drop sequence CALBOARD_SEQ;

create sequence ACCOUNT_SEQ;

SELECT * FROM CALBOARD;

--일정 추가--
INSERT INTO CALBOARD VALUES (CALBOARD_SEQ.NEXTVAL, 'testnong', '일정제목1', '일정내용1', '202109291540', SYSDATE);


--일정 목록 조회--
SELECT SEQ, ID, TITLE, CONTENT, MDATE, REGDATE
FROM CALBOARD
WHERE ID='hk' AND SUBSTR(MDATE,1,8) = '20210929'
ORDER BY MDATE ;

--일정 상세조회--
SELECT SEQ, ID, TITLE, CONTENT, MDATE, REGDATE
FROM CALBOARD
WHERE SEQ = 1;

-- 일정 수정하기--
UPDATE CALBOARD SET 
TITLE = '제목수정',
CONTENT='내용수정',
MDATE='202104081520',
REGDATE=SYSDATE
WHERE SEQ= 1;

-- 일정 개수구하기--
SELECT COUNT(*)
FROM CALBOARD
WHERE ID = 'HT' AND SUBSTR(MDATE, 1, 8) = '20210406';

-- 해당 달의 날마다 존재하는 일정의 개수를 3개까지 구하기
SELECT RN, SEQ, ID, TITLE, CONTENT, MDATE, REGDATE
FROM (	SELECT ROW_NUMBER() OVER(PARTITION BY SUBSTR(MDATE,1,8) ORDER BY MDATE) AS RN , 
		SEQ,ID,TITLE,CONTENT,MDATE,REGDATE
		FROM CALBOARD
		WHERE ID = 'hk' AND SUBSTR(MDATE,1,6) ='202109'
	)
WHERE RN BETWEEN 1 AND 3 ;
